# Generated by Django 6.0.6 on 2026-07-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Languages & Querying', 'Languages'), ('Frameworks, Libraries & Tools', 'Frameworks'), ('Cloud & Infrastructure', 'Cloud'), ('Technical Concepts', 'Concepts')], max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
