# Generated by Django 6.0.6 on 2026-07-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon_key',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
