# Generated by Django 6.0.6 on 2026-07-29 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_rename_profile_to_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('icon_key', models.SlugField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies', to='userprofile.userprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
