# Generated by Django 6.0.6 on 2026-07-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
