# Generated by Django 6.0.6 on 2026-07-31 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_leetcode_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('institution_icon_key', models.SlugField(blank=True, default='')),
                ('degree', models.CharField(max_length=200)),
                ('degree_icon_key', models.SlugField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='userprofile.userprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
