# Generated by Django 6.0.7 on 2026-08-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
