# Generated by Django 6.0.7 on 2026-08-05 11:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_tool_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillAgentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('Skill', 'Skill'), ('Agent', 'Agent')], max_length=20)),
                ('description', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('video_url', models.URLField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_agent_entries', to='tools.tool')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
