# Generated by Django 6.0.7 on 2026-08-05 13:12

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_skillagententry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('how_it_works', models.TextField()),
                ('recognition_signals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=list)),
                ('code_solution', models.TextField()),
                ('code_language', models.CharField(default='python', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_patterns', to='tools.tool')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuideExampleProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_problems', to='tools.guidepattern')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
