# Generated by Django 6.0.7 on 2026-08-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_guidepattern_guideexampleproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideexampleproblem',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
