# Generated by Django 6.0.7 on 2026-08-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_guideexampleproblem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidepattern',
            name='diagram_svg',
            field=models.TextField(blank=True, default=''),
        ),
    ]
