# Generated by Django 6.0.7 on 2026-08-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_guidepattern_diagram_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('Demo', 'Demo'), ('Tool', 'Tool'), ('Guide', 'Guide')], max_length=20),
        ),
    ]
