# Generated by Django 6.0.6 on 2026-07-03 11:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('bullets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
