# Generated by Django 6.0.6 on 2026-07-04 15:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='bullets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), default=list),
        ),
    ]
