# Generated by Django 6.0.7 on 2026-07-31 16:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_increase_bullet_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='bullets',
        ),
        migrations.CreateModel(
            name='ExperienceBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='experience.experience')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
