# Generated by Django 6.0.7 on 2026-07-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_remove_experience_bullets_experiencebullet'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_icon_key',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
